services:
  itunes-proxy-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5000:5000"
    networks:
      - task-net
  itunes-proxy-ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "8080:8080"
    networks:
      - task-net

networks:
  task-net:
    driver: bridge

