FROM node:20-alpine
EXPOSE 5000
WORKDIR /app
# copy all contents for the folder itunes-proxy-api to the /app folder
COPY ./itunes-proxy-api /app
RUN npm install
RUN npm run build
CMD ["node", "dist/index.js"]