openapi: 3.0.0
info:
  title: iTunes Proxy API
  version: 1.0.0
  description: API to search for albums
  contact:
    name: Wilmer Uruchi
    email: twilmer1999@gmail.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

paths:
  /docs:
    get:
      summary: Get Swagger UI
      description: Get Swagger UI
      responses:
        '200':
          description: Swagger UI
          content:
            text/html:
              schema:
                type: string
  /v0/albums:
    get:
      summary: Get Albums
      description: Get Albums
      parameters:
        - name: artistName
          in: query
          description: The name of the artist
          required: true
          schema:
            type: string
        - name: limit
          in: query
          description: The number of albums to return. Same as in the iTunes API.
          required: false
          schema:
            type: integer
            default: 50
            minimum: 1
            maximum: 200
      responses:
        '200':
          description: A list of albums
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlbumCollectionResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    AlbumCollectionResponse:
      type: object
      properties:
        count:
          type: integer
          description: The number of albums
          items:
            type: object
            properties:
              albumName:
                type: string
                description: The album name
              albumUrl:
                type: string
                description: The URL of the album
              artistId:
                type: integer
                description: The artist ID
              artistName:
                type: string
                description: The artist name
              artworkUrl100:
                type: string
                description: The URL of the artwork (100x100)
    Error:
      type: object
      properties:
        message:
          type: string